// Server-side HTML generation for published pages and games.

function esc(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Safely embed arbitrary JSON inside a <script> tag.
// JSON.stringify can produce strings like "</script>" or "<!--" that break
// HTML parsing — replace the angle brackets inside string literals only.
function safeJson(obj) {
  return JSON.stringify(obj).replace(/<\//g, '<\\/').replace(/<!--/g, '<\\!--');
}

const POWERED_STYLE = `position:fixed;bottom:6px;right:8px;font-size:9px;font-family:monospace;opacity:0.2;text-decoration:none;color:inherit;z-index:99999`;

// ─── Game-only publish ────────────────────────────────────────────────────────
// worlds: array of all world objects from the project (game = full set of worlds)
export function generateGameHtml({ worlds, assets, title, description, origin = '' }) {
  const worldsJson = safeJson(worlds);
  const assetsJson = safeJson(assets);
  const pageTitle  = esc(title || worlds[0]?.name || 'TUIFY Game');
  const pageDesc   = esc(description || `Play ${pageTitle} on TUIFY`);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="${pageDesc}">
  <meta property="og:title" content="${pageTitle}">
  <meta property="og:description" content="${pageDesc}">
  <title>${pageTitle}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html, body { width: 100%; height: 100%; background: #0a0a0a; overflow: hidden; }
    #game-root { width: 100%; height: 100%; }
  </style>
</head>
<body>
  <div id="game-root"></div>
  <a href="${origin}" target="_blank" rel="noopener" style="${POWERED_STYLE}">made with TUIFY</a>
  <script>
    window.__TUIFY_WORLDS__ = ${worldsJson};
    window.__TUIFY_ASSETS__ = ${assetsJson};
  </script>
  <script src="${origin}/runtime/tuify-game.js"></script>
</body>
</html>`;
}

// ─── Page-only publish ────────────────────────────────────────────────────────
// pageHtml is the full HTML string generated by the client's exportHTML logic.
// We just inject the TUIFY powered-by link before </body>.
export function generatePageHtml({ pageHtml, origin = '' }) {
  const link = `<a href="${origin}" target="_blank" rel="noopener" style="${POWERED_STYLE}">made with TUIFY</a>`;
  return pageHtml.replace(/<\/body>/i, `${link}\n</body>`);
}

// ─── Page + Game combined publish ─────────────────────────────────────────────
// Injects a floating "▶ Play" button and a fullscreen game overlay into the
// existing page HTML. Everything is self-contained in a single file.
export function generateCombinedHtml({ pageHtml, worlds, assets, title, description, origin = '' }) {
  const worldsJson = safeJson(worlds);
  const assetsJson = safeJson(assets);

  const injection = `
<style>
#_tfy-overlay {
  display:none; position:fixed; inset:0; z-index:9999;
  background:#0a0a0a;
}
#_tfy-overlay.open { display:block; }
#_tfy-back {
  position:fixed; top:12px; left:12px; z-index:10000;
  background:transparent; border:1px solid #33ff33; color:#33ff33;
  font-family:monospace; font-size:11px; padding:4px 10px; cursor:pointer;
  letter-spacing:1px;
}
#_tfy-back:hover { background:rgba(51,255,51,.12); }
#_tfy-play {
  position:fixed; bottom:24px; right:24px; z-index:9998;
  background:transparent; border:2px solid #33ff33; color:#33ff33;
  font-family:monospace; font-size:12px; padding:8px 18px;
  cursor:pointer; letter-spacing:2px; text-transform:uppercase;
  box-shadow:0 0 12px rgba(51,255,51,.3);
}
#_tfy-play:hover { background:rgba(51,255,51,.1); }
#game-root { width:100%; height:100%; }
</style>
<button id="_tfy-play" onclick="document.getElementById('_tfy-overlay').classList.add('open')">&#9654; Play</button>
<div id="_tfy-overlay">
  <button id="_tfy-back" onclick="document.getElementById('_tfy-overlay').classList.remove('open')">&#8592; Back</button>
  <div id="game-root"></div>
</div>
<a href="${origin}" target="_blank" rel="noopener" style="${POWERED_STYLE}">made with TUIFY</a>
<script>
window.__TUIFY_WORLDS__ = ${worldsJson};
window.__TUIFY_ASSETS__ = ${assetsJson};
</script>
<script src="${origin}/runtime/tuify-game.js"></script>`;

  return pageHtml.replace(/<\/body>/i, `${injection}\n</body>`);
}
